### ISSUE TITLE
TIFF format does not show up through 'LOAD' function, and the image can not be classified through "LOAD" function.  

### ISSUE THREAD

**Issue by hanzi4389604** [ai-cfia/nachet-frontend#148] opened 2024-05-07 21:14 UTC
**Describe the bug**
TIFF format does not show up through 'LOAD' function, and the image can not be classified through "LOAD" function.  
**To Reproduce**

1. Go to 'https://ai-cfia.github.io/nachet-frontend/'
2. Click on 'CAPTURE' -> "LOAD" -> 
![1](https://github.com/ai-cfia/nachet-frontend/assets/31482046/6640f7fb-cbbd-4d65-8334-f49327b6801f)
-> "CLASSIFY" ->  

For a TIFF image, check 
[1.zip](https://github.com/ai-cfia/nachet-frontend/files/15241044/1.zip)

3. 
4. See error "Error fetching inference data"

**Expected behavior**
The seeds in the photo should be segmented and classified.
**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows (version, 10, 11, etc.) : Windows
- Browser [e.g. chrome, safari, edge, firefox] : Chrome

**Additional context**

**Comment by ChromaticPanic** [comment] 2024-05-08 01:10
The front end version at that link is 0.2.0 , the current version on the main branch of the front end is 0.8.0 . We'll have to check the deployment process of when main should be deployed. I saw in another end point that the front end version there is 0.4.0 . So not sure why everything is not on par with the current main branch.

**Comment by hanzi4389604** [comment] 2024-05-08 15:55
Humm.. Do you have any idea on which front end version did Taran used to conduct the end-user testing?

**Comment by ChromaticPanic** [comment] 2024-05-08 15:57
> Humm.. Do you have any idea on which front end version did Taran used to conduct the end-user testing?

0.4.0

**Comment by hanzi4389604** [comment] 2024-05-08 16:00
Do you know the link?

**Comment by ChromaticPanic** [comment] 2024-05-08 16:06
Looks like the problem is the current workflow run doesn't have a deploy step for the github pages endpoint

> Do you know the link?

Probably best to DM Taran

**Comment by hanzi4389604** [comment] 2024-05-08 16:23
https://nachet.inspection.alpha.canada.ca/ 
This is the link Taran is using. However, I cannot access this link and the below message showed up:
403 Forbidden
For support, please contact your network administrator or whomever configured Nginx to use Vouch Proxy.
For help with [Vouch Proxy](https://github.com/vouch/vouch-proxy) or to file a bug report, please visit https://github.com/vouch/vouch-proxy

Do you have any idea? Taran should have went through a github verification, but i was not directed into any verification page :)

**Comment by ChromaticPanic** [comment] 2024-05-10 13:11
I get the same thing. I assume this portal is only available if you have the VPN connected.

**Comment by ChromaticPanic** [comment] 2024-05-10 13:42
> https://nachet.inspection.alpha.canada.ca/ This is the link Taran is using. However, I cannot access this link and the below message showed up: 403 Forbidden For support, please contact your network administrator or whomever configured Nginx to use Vouch Proxy. For help with [Vouch Proxy](https://github.com/vouch/vouch-proxy) or to file a bug report, please visit https://github.com/vouch/vouch-proxy
> 
> Do you have any idea? Taran should have went through a github verification, but i was not directed into any verification page :)

The DevOps team merged a fix to update the application on [https://nachet.inspection.alpha.canada.ca/](https://nachet.inspection.alpha.canada.ca/)  can you confirm it is now `> 0.8.0`

**Comment by hanzi4389604** [comment] 2024-05-10 19:56
From my end, the problem looks persists, the exactly same message pop out.

**Comment by ChromaticPanic** [comment] 2024-07-18 14:38
Fixed in 0.9.2

**Closed by ChromaticPanic** 2024-07-18 14:38 UTC
Labels: Validate
